# This is a basic workflow to help you get started with Actions

name:  deployToScratchOrg
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: 
      - main
      - 'feature/*'
      - 'bugfix/*'

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel


jobs:
  deploy-org:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - run: | 
              echo $DEV_HUB_URL > devHubURLFile
              sfdx force:auth:sfdxurl:store -d -f devHubURLFile
              rm devHubURLFile
              chmod +x /${{ github.workspace }}/scripts/createScratchOrg.sh
              sh ${{ github.workspace }}/scripts/createScratchOrg.sh
